# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msg_pkg/to_arduino_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class to_arduino_msg(genpy.Message):
  _md5sum = "71a226260b511ec21d1286ef6c684eb7"
  _type = "msg_pkg/to_arduino_msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 M1_speed
float32 M2_speed
int32 M1_encoder_speed
int32 M2_encoder_speed"""
  __slots__ = ['M1_speed','M2_speed','M1_encoder_speed','M2_encoder_speed']
  _slot_types = ['float32','float32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       M1_speed,M2_speed,M1_encoder_speed,M2_encoder_speed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(to_arduino_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.M1_speed is None:
        self.M1_speed = 0.
      if self.M2_speed is None:
        self.M2_speed = 0.
      if self.M1_encoder_speed is None:
        self.M1_encoder_speed = 0
      if self.M2_encoder_speed is None:
        self.M2_encoder_speed = 0
    else:
      self.M1_speed = 0.
      self.M2_speed = 0.
      self.M1_encoder_speed = 0
      self.M2_encoder_speed = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2f2i().pack(_x.M1_speed, _x.M2_speed, _x.M1_encoder_speed, _x.M2_encoder_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.M1_speed, _x.M2_speed, _x.M1_encoder_speed, _x.M2_encoder_speed,) = _get_struct_2f2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2f2i().pack(_x.M1_speed, _x.M2_speed, _x.M1_encoder_speed, _x.M2_encoder_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.M1_speed, _x.M2_speed, _x.M1_encoder_speed, _x.M2_encoder_speed,) = _get_struct_2f2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f2i = None
def _get_struct_2f2i():
    global _struct_2f2i
    if _struct_2f2i is None:
        _struct_2f2i = struct.Struct("<2f2i")
    return _struct_2f2i
