(cl:in-package msg_pkg-msg)
(cl:export '(AX-VAL
          AX
          AY-VAL
          AY
          AZ-VAL
          AZ
          GX-VAL
          GX
          GY-VAL
          GY
          GZ-VAL
          GZ
          MX-VAL
          MX
          MY-VAL
          MY
          MZ-VAL
          MZ
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          ENCODER1-VAL
          ENCODER1
          ENCODER2-VAL
          ENCODER2
))